#ifndef ENUMERATIONS_H_INCLUDED
#define ENUMERATIONS_H_INCLUDED

enum KeyStatus
{
    KEY_NONE = 0,
    KEY_PRESSED = 1,
    KEY_DOWN = 2,
    KEY_RELEASED = 4,
    KEY_UP = 8
};

enum ObjectType
{
    OBJECT_NONE = 0,
    OBJECT_REAL,
    OBJECT_ABSTRACT,
    OBJECT_LIVING,
    OBJECT_FIELD,
    OBJECT_BOARD
};

#endif // ENUMERATIONS_H_INCLUDED
